# JSON schema for LLM
JSON_SCHEMA =  {
        "source": "Starting location of the buses (e.g., 'Bangalore')",
        "destination": "Destination location of the buses (e.g., 'Hyderabad')",
        "min_fare": "Minimum fare for filtering buses (e.g., 500)",
        "max_fare": "Maximum fare for filtering buses (e.g., 2000)",
        "bus_type": "Type of bus (e.g., 'AC Sleeper', 'Non-AC Seater')",
        "travel_date": "Date of travel in YYYY-MM-DD format (optional)",
        "departure_time": "Filter buses departing after this time (e.g., '18:00')",
        "arrival_time": "Filter buses arriving before this time (e.g., '06:00')",
        "is_ac": "Whether the bus is air-conditioned (true/false)",
        "is_sleeper": "Whether the bus has sleeper berths (true/false)",
        "is_live_tracking_available": "Whether live tracking is available (true/false)",
        "is_mticket_enabled": "Whether m-ticket (mobile ticket) is accepted (true/false)",
        "ratings_above": "Filter buses with ratings above this value (e.g., 4.5)",
        "operatorId": "Unique identifier for the bus operator",
        "travelsName": "Name of the bus operator or travel agency",
        "routeId": "Unique identifier for the bus route",
        "serviceName": "Name or label of the bus service (e.g., 'Express Service')",
        "serviceId": "Unique identifier for the bus service",
        "operatorLogoPath": "File path or URL of the bus operator’s logo image",
        "boReqParams": "Additional request parameters provided by the bus operator (BO)",
        "cancellationPolicy": "Rules and conditions for ticket cancellation",
        "isPartialCancellationAllowed": "Whether partial cancellation (for some passengers only) is allowed",
        "isSeatLayoutAvailable": "Whether seat layout information is available",
        "serviceNotes": "Special notes or instructions about the bus service",
        "inventoryData": "Raw data about seat availability, inventory, and booking rules",
        "journeyDurationMin": "Total journey duration of the bus from start boarding point to end dropping point in minutes",
        "firstBpTime": "Departure time of the first boarding point",
        "doj": "Date of journey",
        "rescheduleTime": "New departure time if the bus is rescheduled",
        "standardBpName": "Standardized boarding point name (e.g., 'Hebbal')",
        "standardBpIdentifier": "Unique identifier for the boarding point",
        "standardDpName": "Standardized dropping point name (e.g., 'Lakdikapul')",
        "standardDpIdentifier": "Unique identifier for the dropping point",
        "bpCount": "Total number of boarding points for the service",
        "dpCount": "Total number of dropping points for the service",
        "locationSearchParams": "Metadata related to boarding/dropping location search",
        "maxSeatsPerTransaction": "Maximum number of seats bookable in a single transaction",
        "availableWindowSeats": "Number of available window seats",
        "availableSingleSeats": "Number of available single (non-adjacent) seats",
        "availableSeats": "Total number of available seats",
        "totalSeats": "Total seat capacity of the bus",
        "availableAisleSeats": "Number of available aisle seats",
        "availableUpperSeats": "Number of available upper-berth seats (for sleeper buses)",
        "availableLowerSeats": "Number of available lower-berth seats (for sleeper buses)",
        "busImageCount": "Number of bus images available for the listing",
        "totalRatings": "Average rating given to the bus/operator",
        "numberOfReviews": "Total number of user reviews",
        "busScore": "Internal score/quality metric for the bus",
        "perzScore": "Personalized recommendation score (based on personalization algorithms)",
        "fareList": "List of fares for the service (base fare, discounts, dynamic pricing)",
        "vendorCurrency": "Currency in which fares are quoted",
        "campaignType": "Indicates if the service is part of a campaign or promotion",
        "isFlexiOperator": "Whether the operator supports flexible cancellation/rescheduling policies",
        "cheaperThanTerminal": "Whether price is cheaper than offline price",
        "amenities": "List of amenities provided (Wi-Fi, water bottle, charging point, etc.)",
        "isLiveTrackingAvailable": "Whether live tracking of the bus is available",
        "isMticketEnabled": "Whether m-ticket (mobile ticket) is accepted",
        "isAc": "Whether the bus is air-conditioned",
        "isSleeper": "Whether the bus has sleeper berths",
        "isRescheduled": "Whether the bus has been rescheduled",
        "rs555": "Whether the bus is primo bus",
        "redDeal_Offer_is_available": "Whether red Deal offer is available or not",
        "discount_is_available": "Whether any discount is available for that bus",
        "isRTC": "Is that bus a RTC bus i.e bus from regional transport corporation (state govt controlled bus)"
    }


# Mandatory fields to always display
MANDATORY_FIELDS = [
    ("inventoryData.sourceName", "Source"),
    ("inventoryData.destinationName", "Destination"),
    ("travelsName", "Travels Name"),
    ("fareList", "Fare"),
    ("departureTime", "Departure"),
    ("arrivalTime", "Arrival"),
    ("busType", "Bus Type"),
    ("availableSeats", "Available Seats"),
    ("totalRatings", "Ratings")
]

# Parameter → display field mapping
PARAMETER_FIELD_MAP = {
    "source": ("inventoryData.sourceName", "Source"),
    "destination": ("inventoryData.destinationName", "Destination"),
    "min_fare": ("minFare", "Minimum Fare"),
    "max_fare": ("maxFare", "Maximum Fare"),
    "bus_type": ("busType", "Bus Type"),
    "travel_date": ("doj", "Travel Date"),
    "departure_time": ("departureTime", "Departure Time"),
    "arrival_time": ("arrivalTime", "Arrival Time"),
    "is_ac": ("isAc", "AC"),
    "is_sleeper": ("isSleeper", "Sleeper"),
    "is_live_tracking_available": ("isLiveTrackingAvailable", "Live Tracking"),
    "is_mticket_enabled": ("isMticketEnabled", "M-Ticket"),
    "ratings_above": ("totalRatings", "Ratings"),
    "operatorId": ("operatorId", "Operator ID"),
    "travelsName": ("travelsName", "Travels Name"),
    "routeId": ("routeId", "Route ID"),
    "serviceName": ("serviceName", "Service Name"),
    "serviceId": ("serviceId", "Service ID"),
    "operatorLogoPath": ("operatorLogoPath", "Operator Logo"),
    "boReqParams": ("boReqParams", "BO Request Params"),
    "cancellationPolicy": ("cancellationPolicy", "Cancellation Policy"),
    "isPartialCancellationAllowed": ("isPartialCancellationAllowed", "Partial Cancellation Allowed"),
    "isSeatLayoutAvailable": ("isSeatLayoutAvailable", "Seat Layout Available"),
    "serviceNotes": ("serviceNotes", "Service Notes"),
    "inventoryData": ("inventoryData", "Inventory Data"),
    "journeyDurationMin": ("journeyDurationMin", "Journey Duration (min)"),
    "firstBpTime": ("firstBpTime", "First Boarding Point Time"),
    "doj": ("doj", "Date of Journey"),
    "rescheduleTime": ("rescheduleTime", "Reschedule Time"),
    "standardBpName": ("standardBpName", "Boarding Point"),
    "standardBpIdentifier": ("standardBpIdentifier", "Boarding Point ID"),
    "standardDpName": ("standardDpName", "Dropping Point"),
    "standardDpIdentifier": ("standardDpIdentifier", "Dropping Point ID"),
    "bpCount": ("bpCount", "Boarding Points Count"),
    "dpCount": ("dpCount", "Dropping Points Count"),
    "locationSearchParams": ("locationSearchParams", "Location Search Params"),
    "maxSeatsPerTransaction": ("maxSeatsPerTransaction", "Max Seats per Transaction"),
    "availableWindowSeats": ("availableWindowSeats", "Available Window Seats"),
    "availableSingleSeats": ("availableSingleSeats", "Available Single Seats"),
    "availableSeats": ("availableSeats", "Available Seats"),
    "totalSeats": ("totalSeats", "Total Seats"),
    "availableAisleSeats": ("availableAisleSeats", "Available Aisle Seats"),
    "availableUpperSeats": ("availableUpperSeats", "Available Upper Seats"),
    "availableLowerSeats": ("availableLowerSeats", "Available Lower Seats"),
    "busImageCount": ("busImageCount", "Bus Image Count"),
    "totalRatings": ("totalRatings", "Total Ratings"),
    "numberOfReviews": ("numberOfReviews", "Number of Reviews"),
    "busScore": ("busScore", "Bus Score"),
    "perzScore": ("perzScore", "Personalized Score"),
    "fareList": ("fareList", "Fare List"),
    "vendorCurrency": ("vendorCurrency", "Currency"),
    "campaignType": ("campaignType", "Campaign Type"),
    "isFlexiOperator": ("isFlexiOperator", "Flexi Operator"),
    "cheaperThanTerminal": ("cheaperThanTerminal", "Cheaper Than Terminal"),
    "amenities": ("amenities", "Amenities"),
    "isRescheduled": ("isRescheduled", "Rescheduled"),
    "rs555": ("rs555", "Is Primo"),
    "redDeal_Offer_is_available": ("redDeal_Offer_is_available", "Red Deal Available"),
    "discount_is_available": ("discount_is_available", "Discount Available"),
    "isRTC": ("isRTC", "RTC Bus")
}
